### ISSUE TITLE
Results are wrong when loading tensor in cuda

### ISSUE THREAD

**Issue by OuyangWenyu** [rusty1s/pytorch_scatter#256]
I use pytorch 1.9.0 and pytorch_scatter 2.0.9 in windows.  Here is the conda env file I used to install packages:

```yml
name: test
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python==3.9.6
  - pytorch::pytorch==1.9.0
  - pytorch::torchvision
  - pyg::pytorch-scatter=2.0.9
```

The following code is correct when tensors are in CPU but errors occur when loading them to CUDA; the result is wrong:

![some error in torch scatter](https://user-images.githubusercontent.com/10172837/145787500-1f71a9ef-1edc-4a90-9937-09f1903ff61c.png)

How can I fix it?

Thank you!
